name: "Incremental Build"
on:
  push:
    branches: [ main, quay-testing ]

jobs:
  inc-build:
    name: "Build and Publish"
    runs-on: ubuntu-20.04
    
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build wisdom-torchserve Image"
        id: build-torchserve-image
        uses: redhat-actions/buildah-build@v2.3
        with:
          image: wisdom
          tags: unstable ${{ env.SHORT_SHA }}
          oci: true
          context: ./
          dockerfiles: |
            ./torchserve.Containerfile
      - name: "Build wisdom-server Image"
        id: build-server-image
        uses: redhat-actions/buildah-build@v2.3
        with:
          image: ansible_wisdom
          tags: unstable ${{ env.SHORT_SHA }}
          oci: true
          context: ./
          dockerfiles: |
            ./ansible_wisdom.Containerfile

      - name: "Publish wisdom-torchserve Image to quay.io"
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build-torchserve-image.outputs.image }}
          tags: ${{ steps.build-torchserve-image.outputs.tags }}
          registry: quay.io/gleboude
          username: gleboude+github_action
          password: ${{ secrets.QUAY_PASSWORD }}
      - name: "Publish wisdom-torchserve Image to quay.io"
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ steps.build-server-image.outputs.image }}
          tags: ${{ steps.build-server-image.outputs.tags }}
          registry: quay.io/gleboude
          username: gleboude+github_action
          password: ${{ secrets.QUAY_PASSWORD }}
